version: '3'
services:
  consumer:
    build: ./consumer
    volumes:
      - ./consumer:/go/src/github.com/moemoe89/go-rabbitmq-raja/consumer
    container_name: go_rabbitmq_raja_consumer
    restart: always
    tty: true
    depends_on:
      - rabbitmq
    networks:
      - fullstack
  producer:
    build: ./producer
    volumes:
      - ./producer:/go/src/github.com/moemoe89/go-rabbitmq-raja/producer
    container_name: go_rabbitmq_raja_producer
    restart: always
    ports:
      - "8781:8781"
    tty: true
    depends_on:
      - rabbitmq
    networks:
      - fullstack
  rabbitmq:
    image: 'rabbitmq:3.8.2-management-alpine'
    ports:
      - '5671:5672'
      - '15671:15672'
    networks:
      - fullstack
networks:
  fullstack:
    driver: bridge